services:
  api:
    build: .
    container_name: fastapi-application
    environment:
      PORT: 80
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.5'
          memory: 200M
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
